/*
Infrahub-API

Testing VirtualMachineEventsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package hyperstack

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/szczad/hyperstack-api-go"
)

func Test_hyperstack_VirtualMachineEventsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VirtualMachineEventsAPIService ListVirtualMachineEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var virtualMachineId string

		resp, httpRes, err := apiClient.VirtualMachineEventsAPI.ListVirtualMachineEvents(context.Background(), virtualMachineId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
