/*
Infrahub-API

Testing VncUrlAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package hyperstack

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/szczad/hyperstack-api-go"
)

func Test_hyperstack_VncUrlAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VncUrlAPIService GetVNCConsoleLink", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var virtualMachineId int32
		var jobId int32

		resp, httpRes, err := apiClient.VncUrlAPI.GetVNCConsoleLink(context.Background(), virtualMachineId, jobId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VncUrlAPIService RequestConsole", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.VncUrlAPI.RequestConsole(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
