/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
	"time"
)

// checks if the AdminGetContractDetailFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminGetContractDetailFields{}

// AdminGetContractDetailFields struct for AdminGetContractDetailFields
type AdminGetContractDetailFields struct {
	Id *int32 `json:"id,omitempty"`
	OrgId *int32 `json:"org_id,omitempty"`
	Description *string `json:"description,omitempty"`
	StartDate *time.Time `json:"start_date,omitempty"`
	EndDate *time.Time `json:"end_date,omitempty"`
	ExpirationPolicy *int32 `json:"expiration_policy,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewAdminGetContractDetailFields instantiates a new AdminGetContractDetailFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminGetContractDetailFields() *AdminGetContractDetailFields {
	this := AdminGetContractDetailFields{}
	return &this
}

// NewAdminGetContractDetailFieldsWithDefaults instantiates a new AdminGetContractDetailFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminGetContractDetailFieldsWithDefaults() *AdminGetContractDetailFields {
	this := AdminGetContractDetailFields{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AdminGetContractDetailFields) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminGetContractDetailFields) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AdminGetContractDetailFields) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *AdminGetContractDetailFields) SetId(v int32) {
	o.Id = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *AdminGetContractDetailFields) GetOrgId() int32 {
	if o == nil || IsNil(o.OrgId) {
		var ret int32
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminGetContractDetailFields) GetOrgIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrgId) {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *AdminGetContractDetailFields) HasOrgId() bool {
	if o != nil && !IsNil(o.OrgId) {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given int32 and assigns it to the OrgId field.
func (o *AdminGetContractDetailFields) SetOrgId(v int32) {
	o.OrgId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AdminGetContractDetailFields) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminGetContractDetailFields) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AdminGetContractDetailFields) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AdminGetContractDetailFields) SetDescription(v string) {
	o.Description = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *AdminGetContractDetailFields) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminGetContractDetailFields) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *AdminGetContractDetailFields) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *AdminGetContractDetailFields) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *AdminGetContractDetailFields) GetEndDate() time.Time {
	if o == nil || IsNil(o.EndDate) {
		var ret time.Time
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminGetContractDetailFields) GetEndDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *AdminGetContractDetailFields) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given time.Time and assigns it to the EndDate field.
func (o *AdminGetContractDetailFields) SetEndDate(v time.Time) {
	o.EndDate = &v
}

// GetExpirationPolicy returns the ExpirationPolicy field value if set, zero value otherwise.
func (o *AdminGetContractDetailFields) GetExpirationPolicy() int32 {
	if o == nil || IsNil(o.ExpirationPolicy) {
		var ret int32
		return ret
	}
	return *o.ExpirationPolicy
}

// GetExpirationPolicyOk returns a tuple with the ExpirationPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminGetContractDetailFields) GetExpirationPolicyOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpirationPolicy) {
		return nil, false
	}
	return o.ExpirationPolicy, true
}

// HasExpirationPolicy returns a boolean if a field has been set.
func (o *AdminGetContractDetailFields) HasExpirationPolicy() bool {
	if o != nil && !IsNil(o.ExpirationPolicy) {
		return true
	}

	return false
}

// SetExpirationPolicy gets a reference to the given int32 and assigns it to the ExpirationPolicy field.
func (o *AdminGetContractDetailFields) SetExpirationPolicy(v int32) {
	o.ExpirationPolicy = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AdminGetContractDetailFields) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminGetContractDetailFields) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AdminGetContractDetailFields) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AdminGetContractDetailFields) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o AdminGetContractDetailFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminGetContractDetailFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrgId) {
		toSerialize["org_id"] = o.OrgId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	if !IsNil(o.ExpirationPolicy) {
		toSerialize["expiration_policy"] = o.ExpirationPolicy
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableAdminGetContractDetailFields struct {
	value *AdminGetContractDetailFields
	isSet bool
}

func (v NullableAdminGetContractDetailFields) Get() *AdminGetContractDetailFields {
	return v.value
}

func (v *NullableAdminGetContractDetailFields) Set(val *AdminGetContractDetailFields) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminGetContractDetailFields) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminGetContractDetailFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminGetContractDetailFields(val *AdminGetContractDetailFields) *NullableAdminGetContractDetailFields {
	return &NullableAdminGetContractDetailFields{value: val, isSet: true}
}

func (v NullableAdminGetContractDetailFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminGetContractDetailFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


