/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the Environments type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Environments{}

// Environments struct for Environments
type Environments struct {
	Status *bool `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
	Environments []EnvironmentFields `json:"environments,omitempty"`
}

// NewEnvironments instantiates a new Environments object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironments() *Environments {
	this := Environments{}
	return &this
}

// NewEnvironmentsWithDefaults instantiates a new Environments object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentsWithDefaults() *Environments {
	this := Environments{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Environments) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Environments) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Environments) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *Environments) SetStatus(v bool) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Environments) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Environments) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Environments) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Environments) SetMessage(v string) {
	o.Message = &v
}

// GetEnvironments returns the Environments field value if set, zero value otherwise.
func (o *Environments) GetEnvironments() []EnvironmentFields {
	if o == nil || IsNil(o.Environments) {
		var ret []EnvironmentFields
		return ret
	}
	return o.Environments
}

// GetEnvironmentsOk returns a tuple with the Environments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Environments) GetEnvironmentsOk() ([]EnvironmentFields, bool) {
	if o == nil || IsNil(o.Environments) {
		return nil, false
	}
	return o.Environments, true
}

// HasEnvironments returns a boolean if a field has been set.
func (o *Environments) HasEnvironments() bool {
	if o != nil && !IsNil(o.Environments) {
		return true
	}

	return false
}

// SetEnvironments gets a reference to the given []EnvironmentFields and assigns it to the Environments field.
func (o *Environments) SetEnvironments(v []EnvironmentFields) {
	o.Environments = v
}

func (o Environments) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Environments) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Environments) {
		toSerialize["environments"] = o.Environments
	}
	return toSerialize, nil
}

type NullableEnvironments struct {
	value *Environments
	isSet bool
}

func (v NullableEnvironments) Get() *Environments {
	return v.value
}

func (v *NullableEnvironments) Set(val *Environments) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironments) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironments) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironments(val *Environments) *NullableEnvironments {
	return &NullableEnvironments{value: val, isSet: true}
}

func (v NullableEnvironments) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironments) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


