/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the AdminCountResourcesOrganization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminCountResourcesOrganization{}

// AdminCountResourcesOrganization struct for AdminCountResourcesOrganization
type AdminCountResourcesOrganization struct {
	OrganizationId *int32 `json:"organization_id,omitempty"`
	TotalInstances *int32 `json:"total_instances,omitempty"`
	TotalVolumes *int32 `json:"total_volumes,omitempty"`
	TotalContainers *int32 `json:"total_containers,omitempty"`
	TotalClusters *int32 `json:"total_clusters,omitempty"`
}

// NewAdminCountResourcesOrganization instantiates a new AdminCountResourcesOrganization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminCountResourcesOrganization() *AdminCountResourcesOrganization {
	this := AdminCountResourcesOrganization{}
	return &this
}

// NewAdminCountResourcesOrganizationWithDefaults instantiates a new AdminCountResourcesOrganization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminCountResourcesOrganizationWithDefaults() *AdminCountResourcesOrganization {
	this := AdminCountResourcesOrganization{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *AdminCountResourcesOrganization) GetOrganizationId() int32 {
	if o == nil || IsNil(o.OrganizationId) {
		var ret int32
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCountResourcesOrganization) GetOrganizationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *AdminCountResourcesOrganization) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given int32 and assigns it to the OrganizationId field.
func (o *AdminCountResourcesOrganization) SetOrganizationId(v int32) {
	o.OrganizationId = &v
}

// GetTotalInstances returns the TotalInstances field value if set, zero value otherwise.
func (o *AdminCountResourcesOrganization) GetTotalInstances() int32 {
	if o == nil || IsNil(o.TotalInstances) {
		var ret int32
		return ret
	}
	return *o.TotalInstances
}

// GetTotalInstancesOk returns a tuple with the TotalInstances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCountResourcesOrganization) GetTotalInstancesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalInstances) {
		return nil, false
	}
	return o.TotalInstances, true
}

// HasTotalInstances returns a boolean if a field has been set.
func (o *AdminCountResourcesOrganization) HasTotalInstances() bool {
	if o != nil && !IsNil(o.TotalInstances) {
		return true
	}

	return false
}

// SetTotalInstances gets a reference to the given int32 and assigns it to the TotalInstances field.
func (o *AdminCountResourcesOrganization) SetTotalInstances(v int32) {
	o.TotalInstances = &v
}

// GetTotalVolumes returns the TotalVolumes field value if set, zero value otherwise.
func (o *AdminCountResourcesOrganization) GetTotalVolumes() int32 {
	if o == nil || IsNil(o.TotalVolumes) {
		var ret int32
		return ret
	}
	return *o.TotalVolumes
}

// GetTotalVolumesOk returns a tuple with the TotalVolumes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCountResourcesOrganization) GetTotalVolumesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalVolumes) {
		return nil, false
	}
	return o.TotalVolumes, true
}

// HasTotalVolumes returns a boolean if a field has been set.
func (o *AdminCountResourcesOrganization) HasTotalVolumes() bool {
	if o != nil && !IsNil(o.TotalVolumes) {
		return true
	}

	return false
}

// SetTotalVolumes gets a reference to the given int32 and assigns it to the TotalVolumes field.
func (o *AdminCountResourcesOrganization) SetTotalVolumes(v int32) {
	o.TotalVolumes = &v
}

// GetTotalContainers returns the TotalContainers field value if set, zero value otherwise.
func (o *AdminCountResourcesOrganization) GetTotalContainers() int32 {
	if o == nil || IsNil(o.TotalContainers) {
		var ret int32
		return ret
	}
	return *o.TotalContainers
}

// GetTotalContainersOk returns a tuple with the TotalContainers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCountResourcesOrganization) GetTotalContainersOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalContainers) {
		return nil, false
	}
	return o.TotalContainers, true
}

// HasTotalContainers returns a boolean if a field has been set.
func (o *AdminCountResourcesOrganization) HasTotalContainers() bool {
	if o != nil && !IsNil(o.TotalContainers) {
		return true
	}

	return false
}

// SetTotalContainers gets a reference to the given int32 and assigns it to the TotalContainers field.
func (o *AdminCountResourcesOrganization) SetTotalContainers(v int32) {
	o.TotalContainers = &v
}

// GetTotalClusters returns the TotalClusters field value if set, zero value otherwise.
func (o *AdminCountResourcesOrganization) GetTotalClusters() int32 {
	if o == nil || IsNil(o.TotalClusters) {
		var ret int32
		return ret
	}
	return *o.TotalClusters
}

// GetTotalClustersOk returns a tuple with the TotalClusters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCountResourcesOrganization) GetTotalClustersOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalClusters) {
		return nil, false
	}
	return o.TotalClusters, true
}

// HasTotalClusters returns a boolean if a field has been set.
func (o *AdminCountResourcesOrganization) HasTotalClusters() bool {
	if o != nil && !IsNil(o.TotalClusters) {
		return true
	}

	return false
}

// SetTotalClusters gets a reference to the given int32 and assigns it to the TotalClusters field.
func (o *AdminCountResourcesOrganization) SetTotalClusters(v int32) {
	o.TotalClusters = &v
}

func (o AdminCountResourcesOrganization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminCountResourcesOrganization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if !IsNil(o.TotalInstances) {
		toSerialize["total_instances"] = o.TotalInstances
	}
	if !IsNil(o.TotalVolumes) {
		toSerialize["total_volumes"] = o.TotalVolumes
	}
	if !IsNil(o.TotalContainers) {
		toSerialize["total_containers"] = o.TotalContainers
	}
	if !IsNil(o.TotalClusters) {
		toSerialize["total_clusters"] = o.TotalClusters
	}
	return toSerialize, nil
}

type NullableAdminCountResourcesOrganization struct {
	value *AdminCountResourcesOrganization
	isSet bool
}

func (v NullableAdminCountResourcesOrganization) Get() *AdminCountResourcesOrganization {
	return v.value
}

func (v *NullableAdminCountResourcesOrganization) Set(val *AdminCountResourcesOrganization) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminCountResourcesOrganization) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminCountResourcesOrganization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminCountResourcesOrganization(val *AdminCountResourcesOrganization) *NullableAdminCountResourcesOrganization {
	return &NullableAdminCountResourcesOrganization{value: val, isSet: true}
}

func (v NullableAdminCountResourcesOrganization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminCountResourcesOrganization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


