/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
	"time"
)

// checks if the AdminContractFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminContractFields{}

// AdminContractFields struct for AdminContractFields
type AdminContractFields struct {
	Id *int32 `json:"id,omitempty"`
	OrgName *string `json:"org_name,omitempty"`
	Description *string `json:"description,omitempty"`
	StartDate *time.Time `json:"start_date,omitempty"`
	EndDate *time.Time `json:"end_date,omitempty"`
	ExpirationPolicy *int32 `json:"expiration_policy,omitempty"`
	Status *string `json:"status,omitempty"`
	GpuName *string `json:"gpu_name,omitempty"`
	Percent *float32 `json:"percent,omitempty"`
	Amount *float32 `json:"amount,omitempty"`
	DiscountType *string `json:"discount_type,omitempty"`
	ResourceCount *int32 `json:"resource_count,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewAdminContractFields instantiates a new AdminContractFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminContractFields() *AdminContractFields {
	this := AdminContractFields{}
	return &this
}

// NewAdminContractFieldsWithDefaults instantiates a new AdminContractFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminContractFieldsWithDefaults() *AdminContractFields {
	this := AdminContractFields{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AdminContractFields) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminContractFields) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AdminContractFields) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *AdminContractFields) SetId(v int32) {
	o.Id = &v
}

// GetOrgName returns the OrgName field value if set, zero value otherwise.
func (o *AdminContractFields) GetOrgName() string {
	if o == nil || IsNil(o.OrgName) {
		var ret string
		return ret
	}
	return *o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminContractFields) GetOrgNameOk() (*string, bool) {
	if o == nil || IsNil(o.OrgName) {
		return nil, false
	}
	return o.OrgName, true
}

// HasOrgName returns a boolean if a field has been set.
func (o *AdminContractFields) HasOrgName() bool {
	if o != nil && !IsNil(o.OrgName) {
		return true
	}

	return false
}

// SetOrgName gets a reference to the given string and assigns it to the OrgName field.
func (o *AdminContractFields) SetOrgName(v string) {
	o.OrgName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AdminContractFields) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminContractFields) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AdminContractFields) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AdminContractFields) SetDescription(v string) {
	o.Description = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *AdminContractFields) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminContractFields) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *AdminContractFields) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *AdminContractFields) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *AdminContractFields) GetEndDate() time.Time {
	if o == nil || IsNil(o.EndDate) {
		var ret time.Time
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminContractFields) GetEndDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *AdminContractFields) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given time.Time and assigns it to the EndDate field.
func (o *AdminContractFields) SetEndDate(v time.Time) {
	o.EndDate = &v
}

// GetExpirationPolicy returns the ExpirationPolicy field value if set, zero value otherwise.
func (o *AdminContractFields) GetExpirationPolicy() int32 {
	if o == nil || IsNil(o.ExpirationPolicy) {
		var ret int32
		return ret
	}
	return *o.ExpirationPolicy
}

// GetExpirationPolicyOk returns a tuple with the ExpirationPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminContractFields) GetExpirationPolicyOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpirationPolicy) {
		return nil, false
	}
	return o.ExpirationPolicy, true
}

// HasExpirationPolicy returns a boolean if a field has been set.
func (o *AdminContractFields) HasExpirationPolicy() bool {
	if o != nil && !IsNil(o.ExpirationPolicy) {
		return true
	}

	return false
}

// SetExpirationPolicy gets a reference to the given int32 and assigns it to the ExpirationPolicy field.
func (o *AdminContractFields) SetExpirationPolicy(v int32) {
	o.ExpirationPolicy = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AdminContractFields) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminContractFields) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AdminContractFields) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AdminContractFields) SetStatus(v string) {
	o.Status = &v
}

// GetGpuName returns the GpuName field value if set, zero value otherwise.
func (o *AdminContractFields) GetGpuName() string {
	if o == nil || IsNil(o.GpuName) {
		var ret string
		return ret
	}
	return *o.GpuName
}

// GetGpuNameOk returns a tuple with the GpuName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminContractFields) GetGpuNameOk() (*string, bool) {
	if o == nil || IsNil(o.GpuName) {
		return nil, false
	}
	return o.GpuName, true
}

// HasGpuName returns a boolean if a field has been set.
func (o *AdminContractFields) HasGpuName() bool {
	if o != nil && !IsNil(o.GpuName) {
		return true
	}

	return false
}

// SetGpuName gets a reference to the given string and assigns it to the GpuName field.
func (o *AdminContractFields) SetGpuName(v string) {
	o.GpuName = &v
}

// GetPercent returns the Percent field value if set, zero value otherwise.
func (o *AdminContractFields) GetPercent() float32 {
	if o == nil || IsNil(o.Percent) {
		var ret float32
		return ret
	}
	return *o.Percent
}

// GetPercentOk returns a tuple with the Percent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminContractFields) GetPercentOk() (*float32, bool) {
	if o == nil || IsNil(o.Percent) {
		return nil, false
	}
	return o.Percent, true
}

// HasPercent returns a boolean if a field has been set.
func (o *AdminContractFields) HasPercent() bool {
	if o != nil && !IsNil(o.Percent) {
		return true
	}

	return false
}

// SetPercent gets a reference to the given float32 and assigns it to the Percent field.
func (o *AdminContractFields) SetPercent(v float32) {
	o.Percent = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *AdminContractFields) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminContractFields) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *AdminContractFields) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *AdminContractFields) SetAmount(v float32) {
	o.Amount = &v
}

// GetDiscountType returns the DiscountType field value if set, zero value otherwise.
func (o *AdminContractFields) GetDiscountType() string {
	if o == nil || IsNil(o.DiscountType) {
		var ret string
		return ret
	}
	return *o.DiscountType
}

// GetDiscountTypeOk returns a tuple with the DiscountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminContractFields) GetDiscountTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DiscountType) {
		return nil, false
	}
	return o.DiscountType, true
}

// HasDiscountType returns a boolean if a field has been set.
func (o *AdminContractFields) HasDiscountType() bool {
	if o != nil && !IsNil(o.DiscountType) {
		return true
	}

	return false
}

// SetDiscountType gets a reference to the given string and assigns it to the DiscountType field.
func (o *AdminContractFields) SetDiscountType(v string) {
	o.DiscountType = &v
}

// GetResourceCount returns the ResourceCount field value if set, zero value otherwise.
func (o *AdminContractFields) GetResourceCount() int32 {
	if o == nil || IsNil(o.ResourceCount) {
		var ret int32
		return ret
	}
	return *o.ResourceCount
}

// GetResourceCountOk returns a tuple with the ResourceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminContractFields) GetResourceCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ResourceCount) {
		return nil, false
	}
	return o.ResourceCount, true
}

// HasResourceCount returns a boolean if a field has been set.
func (o *AdminContractFields) HasResourceCount() bool {
	if o != nil && !IsNil(o.ResourceCount) {
		return true
	}

	return false
}

// SetResourceCount gets a reference to the given int32 and assigns it to the ResourceCount field.
func (o *AdminContractFields) SetResourceCount(v int32) {
	o.ResourceCount = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AdminContractFields) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminContractFields) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AdminContractFields) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AdminContractFields) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o AdminContractFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminContractFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrgName) {
		toSerialize["org_name"] = o.OrgName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	if !IsNil(o.ExpirationPolicy) {
		toSerialize["expiration_policy"] = o.ExpirationPolicy
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.GpuName) {
		toSerialize["gpu_name"] = o.GpuName
	}
	if !IsNil(o.Percent) {
		toSerialize["percent"] = o.Percent
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.DiscountType) {
		toSerialize["discount_type"] = o.DiscountType
	}
	if !IsNil(o.ResourceCount) {
		toSerialize["resource_count"] = o.ResourceCount
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableAdminContractFields struct {
	value *AdminContractFields
	isSet bool
}

func (v NullableAdminContractFields) Get() *AdminContractFields {
	return v.value
}

func (v *NullableAdminContractFields) Set(val *AdminContractFields) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminContractFields) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminContractFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminContractFields(val *AdminContractFields) *NullableAdminContractFields {
	return &NullableAdminContractFields{value: val, isSet: true}
}

func (v NullableAdminContractFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminContractFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


