/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the InstancesSummaryAdmin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstancesSummaryAdmin{}

// InstancesSummaryAdmin struct for InstancesSummaryAdmin
type InstancesSummaryAdmin struct {
	Status *bool `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
	Instances []InstancesSummaryFields `json:"instances,omitempty"`
}

// NewInstancesSummaryAdmin instantiates a new InstancesSummaryAdmin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstancesSummaryAdmin() *InstancesSummaryAdmin {
	this := InstancesSummaryAdmin{}
	return &this
}

// NewInstancesSummaryAdminWithDefaults instantiates a new InstancesSummaryAdmin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstancesSummaryAdminWithDefaults() *InstancesSummaryAdmin {
	this := InstancesSummaryAdmin{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InstancesSummaryAdmin) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstancesSummaryAdmin) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InstancesSummaryAdmin) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *InstancesSummaryAdmin) SetStatus(v bool) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *InstancesSummaryAdmin) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstancesSummaryAdmin) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *InstancesSummaryAdmin) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *InstancesSummaryAdmin) SetMessage(v string) {
	o.Message = &v
}

// GetInstances returns the Instances field value if set, zero value otherwise.
func (o *InstancesSummaryAdmin) GetInstances() []InstancesSummaryFields {
	if o == nil || IsNil(o.Instances) {
		var ret []InstancesSummaryFields
		return ret
	}
	return o.Instances
}

// GetInstancesOk returns a tuple with the Instances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstancesSummaryAdmin) GetInstancesOk() ([]InstancesSummaryFields, bool) {
	if o == nil || IsNil(o.Instances) {
		return nil, false
	}
	return o.Instances, true
}

// HasInstances returns a boolean if a field has been set.
func (o *InstancesSummaryAdmin) HasInstances() bool {
	if o != nil && !IsNil(o.Instances) {
		return true
	}

	return false
}

// SetInstances gets a reference to the given []InstancesSummaryFields and assigns it to the Instances field.
func (o *InstancesSummaryAdmin) SetInstances(v []InstancesSummaryFields) {
	o.Instances = v
}

func (o InstancesSummaryAdmin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstancesSummaryAdmin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Instances) {
		toSerialize["instances"] = o.Instances
	}
	return toSerialize, nil
}

type NullableInstancesSummaryAdmin struct {
	value *InstancesSummaryAdmin
	isSet bool
}

func (v NullableInstancesSummaryAdmin) Get() *InstancesSummaryAdmin {
	return v.value
}

func (v *NullableInstancesSummaryAdmin) Set(val *InstancesSummaryAdmin) {
	v.value = val
	v.isSet = true
}

func (v NullableInstancesSummaryAdmin) IsSet() bool {
	return v.isSet
}

func (v *NullableInstancesSummaryAdmin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstancesSummaryAdmin(val *InstancesSummaryAdmin) *NullableInstancesSummaryAdmin {
	return &NullableInstancesSummaryAdmin{value: val, isSet: true}
}

func (v NullableInstancesSummaryAdmin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstancesSummaryAdmin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


