/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the GetContractsListResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetContractsListResponseModel{}

// GetContractsListResponseModel struct for GetContractsListResponseModel
type GetContractsListResponseModel struct {
	Status *bool `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
	Contracts []AdminContractFields `json:"contracts,omitempty"`
	Count *int32 `json:"count,omitempty"`
}

// NewGetContractsListResponseModel instantiates a new GetContractsListResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetContractsListResponseModel() *GetContractsListResponseModel {
	this := GetContractsListResponseModel{}
	return &this
}

// NewGetContractsListResponseModelWithDefaults instantiates a new GetContractsListResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetContractsListResponseModelWithDefaults() *GetContractsListResponseModel {
	this := GetContractsListResponseModel{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetContractsListResponseModel) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContractsListResponseModel) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetContractsListResponseModel) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *GetContractsListResponseModel) SetStatus(v bool) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetContractsListResponseModel) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContractsListResponseModel) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetContractsListResponseModel) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetContractsListResponseModel) SetMessage(v string) {
	o.Message = &v
}

// GetContracts returns the Contracts field value if set, zero value otherwise.
func (o *GetContractsListResponseModel) GetContracts() []AdminContractFields {
	if o == nil || IsNil(o.Contracts) {
		var ret []AdminContractFields
		return ret
	}
	return o.Contracts
}

// GetContractsOk returns a tuple with the Contracts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContractsListResponseModel) GetContractsOk() ([]AdminContractFields, bool) {
	if o == nil || IsNil(o.Contracts) {
		return nil, false
	}
	return o.Contracts, true
}

// HasContracts returns a boolean if a field has been set.
func (o *GetContractsListResponseModel) HasContracts() bool {
	if o != nil && !IsNil(o.Contracts) {
		return true
	}

	return false
}

// SetContracts gets a reference to the given []AdminContractFields and assigns it to the Contracts field.
func (o *GetContractsListResponseModel) SetContracts(v []AdminContractFields) {
	o.Contracts = v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *GetContractsListResponseModel) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContractsListResponseModel) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *GetContractsListResponseModel) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *GetContractsListResponseModel) SetCount(v int32) {
	o.Count = &v
}

func (o GetContractsListResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetContractsListResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Contracts) {
		toSerialize["contracts"] = o.Contracts
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableGetContractsListResponseModel struct {
	value *GetContractsListResponseModel
	isSet bool
}

func (v NullableGetContractsListResponseModel) Get() *GetContractsListResponseModel {
	return v.value
}

func (v *NullableGetContractsListResponseModel) Set(val *GetContractsListResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGetContractsListResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGetContractsListResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetContractsListResponseModel(val *GetContractsListResponseModel) *NullableGetContractsListResponseModel {
	return &NullableGetContractsListResponseModel{value: val, isSet: true}
}

func (v NullableGetContractsListResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetContractsListResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


