/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
	"time"
)

// checks if the CustomerContractFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerContractFields{}

// CustomerContractFields struct for CustomerContractFields
type CustomerContractFields struct {
	Id *int32 `json:"id,omitempty"`
	OrgId *int32 `json:"org_id,omitempty"`
	Description *string `json:"description,omitempty"`
	StartDate *time.Time `json:"start_date,omitempty"`
	EndDate *time.Time `json:"end_date,omitempty"`
	ExpirationPolicy *int32 `json:"expiration_policy,omitempty"`
	Status *string `json:"status,omitempty"`
	Discounts []DiscountPlanFields `json:"discounts,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewCustomerContractFields instantiates a new CustomerContractFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerContractFields() *CustomerContractFields {
	this := CustomerContractFields{}
	return &this
}

// NewCustomerContractFieldsWithDefaults instantiates a new CustomerContractFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerContractFieldsWithDefaults() *CustomerContractFields {
	this := CustomerContractFields{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CustomerContractFields) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerContractFields) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CustomerContractFields) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *CustomerContractFields) SetId(v int32) {
	o.Id = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *CustomerContractFields) GetOrgId() int32 {
	if o == nil || IsNil(o.OrgId) {
		var ret int32
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerContractFields) GetOrgIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrgId) {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *CustomerContractFields) HasOrgId() bool {
	if o != nil && !IsNil(o.OrgId) {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given int32 and assigns it to the OrgId field.
func (o *CustomerContractFields) SetOrgId(v int32) {
	o.OrgId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CustomerContractFields) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerContractFields) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CustomerContractFields) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CustomerContractFields) SetDescription(v string) {
	o.Description = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *CustomerContractFields) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerContractFields) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *CustomerContractFields) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *CustomerContractFields) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *CustomerContractFields) GetEndDate() time.Time {
	if o == nil || IsNil(o.EndDate) {
		var ret time.Time
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerContractFields) GetEndDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *CustomerContractFields) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given time.Time and assigns it to the EndDate field.
func (o *CustomerContractFields) SetEndDate(v time.Time) {
	o.EndDate = &v
}

// GetExpirationPolicy returns the ExpirationPolicy field value if set, zero value otherwise.
func (o *CustomerContractFields) GetExpirationPolicy() int32 {
	if o == nil || IsNil(o.ExpirationPolicy) {
		var ret int32
		return ret
	}
	return *o.ExpirationPolicy
}

// GetExpirationPolicyOk returns a tuple with the ExpirationPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerContractFields) GetExpirationPolicyOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpirationPolicy) {
		return nil, false
	}
	return o.ExpirationPolicy, true
}

// HasExpirationPolicy returns a boolean if a field has been set.
func (o *CustomerContractFields) HasExpirationPolicy() bool {
	if o != nil && !IsNil(o.ExpirationPolicy) {
		return true
	}

	return false
}

// SetExpirationPolicy gets a reference to the given int32 and assigns it to the ExpirationPolicy field.
func (o *CustomerContractFields) SetExpirationPolicy(v int32) {
	o.ExpirationPolicy = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CustomerContractFields) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerContractFields) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CustomerContractFields) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CustomerContractFields) SetStatus(v string) {
	o.Status = &v
}

// GetDiscounts returns the Discounts field value if set, zero value otherwise.
func (o *CustomerContractFields) GetDiscounts() []DiscountPlanFields {
	if o == nil || IsNil(o.Discounts) {
		var ret []DiscountPlanFields
		return ret
	}
	return o.Discounts
}

// GetDiscountsOk returns a tuple with the Discounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerContractFields) GetDiscountsOk() ([]DiscountPlanFields, bool) {
	if o == nil || IsNil(o.Discounts) {
		return nil, false
	}
	return o.Discounts, true
}

// HasDiscounts returns a boolean if a field has been set.
func (o *CustomerContractFields) HasDiscounts() bool {
	if o != nil && !IsNil(o.Discounts) {
		return true
	}

	return false
}

// SetDiscounts gets a reference to the given []DiscountPlanFields and assigns it to the Discounts field.
func (o *CustomerContractFields) SetDiscounts(v []DiscountPlanFields) {
	o.Discounts = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CustomerContractFields) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerContractFields) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CustomerContractFields) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *CustomerContractFields) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o CustomerContractFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerContractFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrgId) {
		toSerialize["org_id"] = o.OrgId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	if !IsNil(o.ExpirationPolicy) {
		toSerialize["expiration_policy"] = o.ExpirationPolicy
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Discounts) {
		toSerialize["discounts"] = o.Discounts
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableCustomerContractFields struct {
	value *CustomerContractFields
	isSet bool
}

func (v NullableCustomerContractFields) Get() *CustomerContractFields {
	return v.value
}

func (v *NullableCustomerContractFields) Set(val *CustomerContractFields) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerContractFields) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerContractFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerContractFields(val *CustomerContractFields) *NullableCustomerContractFields {
	return &NullableCustomerContractFields{value: val, isSet: true}
}

func (v NullableCustomerContractFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerContractFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


