/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the Adminthresholdpostpayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Adminthresholdpostpayload{}

// Adminthresholdpostpayload struct for Adminthresholdpostpayload
type Adminthresholdpostpayload struct {
	Threshold *float32 `json:"threshold,omitempty"`
}

// NewAdminthresholdpostpayload instantiates a new Adminthresholdpostpayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminthresholdpostpayload() *Adminthresholdpostpayload {
	this := Adminthresholdpostpayload{}
	return &this
}

// NewAdminthresholdpostpayloadWithDefaults instantiates a new Adminthresholdpostpayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminthresholdpostpayloadWithDefaults() *Adminthresholdpostpayload {
	this := Adminthresholdpostpayload{}
	return &this
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *Adminthresholdpostpayload) GetThreshold() float32 {
	if o == nil || IsNil(o.Threshold) {
		var ret float32
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Adminthresholdpostpayload) GetThresholdOk() (*float32, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *Adminthresholdpostpayload) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given float32 and assigns it to the Threshold field.
func (o *Adminthresholdpostpayload) SetThreshold(v float32) {
	o.Threshold = &v
}

func (o Adminthresholdpostpayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Adminthresholdpostpayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	return toSerialize, nil
}

type NullableAdminthresholdpostpayload struct {
	value *Adminthresholdpostpayload
	isSet bool
}

func (v NullableAdminthresholdpostpayload) Get() *Adminthresholdpostpayload {
	return v.value
}

func (v *NullableAdminthresholdpostpayload) Set(val *Adminthresholdpostpayload) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminthresholdpostpayload) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminthresholdpostpayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminthresholdpostpayload(val *Adminthresholdpostpayload) *NullableAdminthresholdpostpayload {
	return &NullableAdminthresholdpostpayload{value: val, isSet: true}
}

func (v NullableAdminthresholdpostpayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminthresholdpostpayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


