/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the AdminCreateContractResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminCreateContractResponseModel{}

// AdminCreateContractResponseModel struct for AdminCreateContractResponseModel
type AdminCreateContractResponseModel struct {
	Status *bool `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
	Contract *CreateContarctFields `json:"contract,omitempty"`
}

// NewAdminCreateContractResponseModel instantiates a new AdminCreateContractResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminCreateContractResponseModel() *AdminCreateContractResponseModel {
	this := AdminCreateContractResponseModel{}
	return &this
}

// NewAdminCreateContractResponseModelWithDefaults instantiates a new AdminCreateContractResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminCreateContractResponseModelWithDefaults() *AdminCreateContractResponseModel {
	this := AdminCreateContractResponseModel{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AdminCreateContractResponseModel) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateContractResponseModel) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AdminCreateContractResponseModel) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *AdminCreateContractResponseModel) SetStatus(v bool) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AdminCreateContractResponseModel) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateContractResponseModel) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AdminCreateContractResponseModel) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AdminCreateContractResponseModel) SetMessage(v string) {
	o.Message = &v
}

// GetContract returns the Contract field value if set, zero value otherwise.
func (o *AdminCreateContractResponseModel) GetContract() CreateContarctFields {
	if o == nil || IsNil(o.Contract) {
		var ret CreateContarctFields
		return ret
	}
	return *o.Contract
}

// GetContractOk returns a tuple with the Contract field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCreateContractResponseModel) GetContractOk() (*CreateContarctFields, bool) {
	if o == nil || IsNil(o.Contract) {
		return nil, false
	}
	return o.Contract, true
}

// HasContract returns a boolean if a field has been set.
func (o *AdminCreateContractResponseModel) HasContract() bool {
	if o != nil && !IsNil(o.Contract) {
		return true
	}

	return false
}

// SetContract gets a reference to the given CreateContarctFields and assigns it to the Contract field.
func (o *AdminCreateContractResponseModel) SetContract(v CreateContarctFields) {
	o.Contract = &v
}

func (o AdminCreateContractResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminCreateContractResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Contract) {
		toSerialize["contract"] = o.Contract
	}
	return toSerialize, nil
}

type NullableAdminCreateContractResponseModel struct {
	value *AdminCreateContractResponseModel
	isSet bool
}

func (v NullableAdminCreateContractResponseModel) Get() *AdminCreateContractResponseModel {
	return v.value
}

func (v *NullableAdminCreateContractResponseModel) Set(val *AdminCreateContractResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminCreateContractResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminCreateContractResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminCreateContractResponseModel(val *AdminCreateContractResponseModel) *NullableAdminCreateContractResponseModel {
	return &NullableAdminCreateContractResponseModel{value: val, isSet: true}
}

func (v NullableAdminCreateContractResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminCreateContractResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


