/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the AdminImageAdminResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminImageAdminResponse{}

// AdminImageAdminResponse struct for AdminImageAdminResponse
type AdminImageAdminResponse struct {
	Status *bool `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
	Image *AdminImageAdminResponseImage `json:"image,omitempty"`
}

// NewAdminImageAdminResponse instantiates a new AdminImageAdminResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminImageAdminResponse() *AdminImageAdminResponse {
	this := AdminImageAdminResponse{}
	return &this
}

// NewAdminImageAdminResponseWithDefaults instantiates a new AdminImageAdminResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminImageAdminResponseWithDefaults() *AdminImageAdminResponse {
	this := AdminImageAdminResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AdminImageAdminResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminImageAdminResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AdminImageAdminResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *AdminImageAdminResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AdminImageAdminResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminImageAdminResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AdminImageAdminResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AdminImageAdminResponse) SetMessage(v string) {
	o.Message = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *AdminImageAdminResponse) GetImage() AdminImageAdminResponseImage {
	if o == nil || IsNil(o.Image) {
		var ret AdminImageAdminResponseImage
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminImageAdminResponse) GetImageOk() (*AdminImageAdminResponseImage, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *AdminImageAdminResponse) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given AdminImageAdminResponseImage and assigns it to the Image field.
func (o *AdminImageAdminResponse) SetImage(v AdminImageAdminResponseImage) {
	o.Image = &v
}

func (o AdminImageAdminResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminImageAdminResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	return toSerialize, nil
}

type NullableAdminImageAdminResponse struct {
	value *AdminImageAdminResponse
	isSet bool
}

func (v NullableAdminImageAdminResponse) Get() *AdminImageAdminResponse {
	return v.value
}

func (v *NullableAdminImageAdminResponse) Set(val *AdminImageAdminResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminImageAdminResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminImageAdminResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminImageAdminResponse(val *AdminImageAdminResponse) *NullableAdminImageAdminResponse {
	return &NullableAdminImageAdminResponse{value: val, isSet: true}
}

func (v NullableAdminImageAdminResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminImageAdminResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


