/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the AdminFlavorResourcesList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminFlavorResourcesList{}

// AdminFlavorResourcesList struct for AdminFlavorResourcesList
type AdminFlavorResourcesList struct {
	Status *bool `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
	Flavors []AdminFlavorResource `json:"flavors,omitempty"`
}

// NewAdminFlavorResourcesList instantiates a new AdminFlavorResourcesList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminFlavorResourcesList() *AdminFlavorResourcesList {
	this := AdminFlavorResourcesList{}
	return &this
}

// NewAdminFlavorResourcesListWithDefaults instantiates a new AdminFlavorResourcesList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminFlavorResourcesListWithDefaults() *AdminFlavorResourcesList {
	this := AdminFlavorResourcesList{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AdminFlavorResourcesList) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminFlavorResourcesList) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AdminFlavorResourcesList) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *AdminFlavorResourcesList) SetStatus(v bool) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AdminFlavorResourcesList) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminFlavorResourcesList) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AdminFlavorResourcesList) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AdminFlavorResourcesList) SetMessage(v string) {
	o.Message = &v
}

// GetFlavors returns the Flavors field value if set, zero value otherwise.
func (o *AdminFlavorResourcesList) GetFlavors() []AdminFlavorResource {
	if o == nil || IsNil(o.Flavors) {
		var ret []AdminFlavorResource
		return ret
	}
	return o.Flavors
}

// GetFlavorsOk returns a tuple with the Flavors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminFlavorResourcesList) GetFlavorsOk() ([]AdminFlavorResource, bool) {
	if o == nil || IsNil(o.Flavors) {
		return nil, false
	}
	return o.Flavors, true
}

// HasFlavors returns a boolean if a field has been set.
func (o *AdminFlavorResourcesList) HasFlavors() bool {
	if o != nil && !IsNil(o.Flavors) {
		return true
	}

	return false
}

// SetFlavors gets a reference to the given []AdminFlavorResource and assigns it to the Flavors field.
func (o *AdminFlavorResourcesList) SetFlavors(v []AdminFlavorResource) {
	o.Flavors = v
}

func (o AdminFlavorResourcesList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminFlavorResourcesList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Flavors) {
		toSerialize["flavors"] = o.Flavors
	}
	return toSerialize, nil
}

type NullableAdminFlavorResourcesList struct {
	value *AdminFlavorResourcesList
	isSet bool
}

func (v NullableAdminFlavorResourcesList) Get() *AdminFlavorResourcesList {
	return v.value
}

func (v *NullableAdminFlavorResourcesList) Set(val *AdminFlavorResourcesList) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminFlavorResourcesList) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminFlavorResourcesList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminFlavorResourcesList(val *AdminFlavorResourcesList) *NullableAdminFlavorResourcesList {
	return &NullableAdminFlavorResourcesList{value: val, isSet: true}
}

func (v NullableAdminFlavorResourcesList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminFlavorResourcesList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


