/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the GetApiKeyResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetApiKeyResponseModel{}

// GetApiKeyResponseModel struct for GetApiKeyResponseModel
type GetApiKeyResponseModel struct {
	Status *bool `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
	ApiKey *ApiKeyFields `json:"api_key,omitempty"`
}

// NewGetApiKeyResponseModel instantiates a new GetApiKeyResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetApiKeyResponseModel() *GetApiKeyResponseModel {
	this := GetApiKeyResponseModel{}
	return &this
}

// NewGetApiKeyResponseModelWithDefaults instantiates a new GetApiKeyResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetApiKeyResponseModelWithDefaults() *GetApiKeyResponseModel {
	this := GetApiKeyResponseModel{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetApiKeyResponseModel) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiKeyResponseModel) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetApiKeyResponseModel) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *GetApiKeyResponseModel) SetStatus(v bool) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetApiKeyResponseModel) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiKeyResponseModel) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetApiKeyResponseModel) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetApiKeyResponseModel) SetMessage(v string) {
	o.Message = &v
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise.
func (o *GetApiKeyResponseModel) GetApiKey() ApiKeyFields {
	if o == nil || IsNil(o.ApiKey) {
		var ret ApiKeyFields
		return ret
	}
	return *o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiKeyResponseModel) GetApiKeyOk() (*ApiKeyFields, bool) {
	if o == nil || IsNil(o.ApiKey) {
		return nil, false
	}
	return o.ApiKey, true
}

// HasApiKey returns a boolean if a field has been set.
func (o *GetApiKeyResponseModel) HasApiKey() bool {
	if o != nil && !IsNil(o.ApiKey) {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given ApiKeyFields and assigns it to the ApiKey field.
func (o *GetApiKeyResponseModel) SetApiKey(v ApiKeyFields) {
	o.ApiKey = &v
}

func (o GetApiKeyResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetApiKeyResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.ApiKey) {
		toSerialize["api_key"] = o.ApiKey
	}
	return toSerialize, nil
}

type NullableGetApiKeyResponseModel struct {
	value *GetApiKeyResponseModel
	isSet bool
}

func (v NullableGetApiKeyResponseModel) Get() *GetApiKeyResponseModel {
	return v.value
}

func (v *NullableGetApiKeyResponseModel) Set(val *GetApiKeyResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGetApiKeyResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGetApiKeyResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetApiKeyResponseModel(val *GetApiKeyResponseModel) *NullableGetApiKeyResponseModel {
	return &NullableGetApiKeyResponseModel{value: val, isSet: true}
}

func (v NullableGetApiKeyResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetApiKeyResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


