/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
	"time"
)

// checks if the AdminInstanceResources type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminInstanceResources{}

// AdminInstanceResources struct for AdminInstanceResources
type AdminInstanceResources struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	OpenstackId *string `json:"openstack_id,omitempty"`
	Host *string `json:"host,omitempty"`
	Status *string `json:"status,omitempty"`
	Flavor *AdminFlavorResource `json:"flavor,omitempty"`
	ImageId *int32 `json:"image_id,omitempty"`
	VolumeId *int32 `json:"volume_id,omitempty"`
	KeypairName *string `json:"keypair_name,omitempty"`
	FixedIp *string `json:"fixed_ip,omitempty"`
	FloatingIp *string `json:"floating_ip,omitempty"`
	ContractId *int32 `json:"contract_id,omitempty"`
	FloatingIpStatus *string `json:"floating_ip_status,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewAdminInstanceResources instantiates a new AdminInstanceResources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminInstanceResources() *AdminInstanceResources {
	this := AdminInstanceResources{}
	return &this
}

// NewAdminInstanceResourcesWithDefaults instantiates a new AdminInstanceResources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminInstanceResourcesWithDefaults() *AdminInstanceResources {
	this := AdminInstanceResources{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *AdminInstanceResources) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AdminInstanceResources) SetName(v string) {
	o.Name = &v
}

// GetOpenstackId returns the OpenstackId field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetOpenstackId() string {
	if o == nil || IsNil(o.OpenstackId) {
		var ret string
		return ret
	}
	return *o.OpenstackId
}

// GetOpenstackIdOk returns a tuple with the OpenstackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetOpenstackIdOk() (*string, bool) {
	if o == nil || IsNil(o.OpenstackId) {
		return nil, false
	}
	return o.OpenstackId, true
}

// HasOpenstackId returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasOpenstackId() bool {
	if o != nil && !IsNil(o.OpenstackId) {
		return true
	}

	return false
}

// SetOpenstackId gets a reference to the given string and assigns it to the OpenstackId field.
func (o *AdminInstanceResources) SetOpenstackId(v string) {
	o.OpenstackId = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *AdminInstanceResources) SetHost(v string) {
	o.Host = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AdminInstanceResources) SetStatus(v string) {
	o.Status = &v
}

// GetFlavor returns the Flavor field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetFlavor() AdminFlavorResource {
	if o == nil || IsNil(o.Flavor) {
		var ret AdminFlavorResource
		return ret
	}
	return *o.Flavor
}

// GetFlavorOk returns a tuple with the Flavor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetFlavorOk() (*AdminFlavorResource, bool) {
	if o == nil || IsNil(o.Flavor) {
		return nil, false
	}
	return o.Flavor, true
}

// HasFlavor returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasFlavor() bool {
	if o != nil && !IsNil(o.Flavor) {
		return true
	}

	return false
}

// SetFlavor gets a reference to the given AdminFlavorResource and assigns it to the Flavor field.
func (o *AdminInstanceResources) SetFlavor(v AdminFlavorResource) {
	o.Flavor = &v
}

// GetImageId returns the ImageId field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetImageId() int32 {
	if o == nil || IsNil(o.ImageId) {
		var ret int32
		return ret
	}
	return *o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetImageIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ImageId) {
		return nil, false
	}
	return o.ImageId, true
}

// HasImageId returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasImageId() bool {
	if o != nil && !IsNil(o.ImageId) {
		return true
	}

	return false
}

// SetImageId gets a reference to the given int32 and assigns it to the ImageId field.
func (o *AdminInstanceResources) SetImageId(v int32) {
	o.ImageId = &v
}

// GetVolumeId returns the VolumeId field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetVolumeId() int32 {
	if o == nil || IsNil(o.VolumeId) {
		var ret int32
		return ret
	}
	return *o.VolumeId
}

// GetVolumeIdOk returns a tuple with the VolumeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetVolumeIdOk() (*int32, bool) {
	if o == nil || IsNil(o.VolumeId) {
		return nil, false
	}
	return o.VolumeId, true
}

// HasVolumeId returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasVolumeId() bool {
	if o != nil && !IsNil(o.VolumeId) {
		return true
	}

	return false
}

// SetVolumeId gets a reference to the given int32 and assigns it to the VolumeId field.
func (o *AdminInstanceResources) SetVolumeId(v int32) {
	o.VolumeId = &v
}

// GetKeypairName returns the KeypairName field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetKeypairName() string {
	if o == nil || IsNil(o.KeypairName) {
		var ret string
		return ret
	}
	return *o.KeypairName
}

// GetKeypairNameOk returns a tuple with the KeypairName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetKeypairNameOk() (*string, bool) {
	if o == nil || IsNil(o.KeypairName) {
		return nil, false
	}
	return o.KeypairName, true
}

// HasKeypairName returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasKeypairName() bool {
	if o != nil && !IsNil(o.KeypairName) {
		return true
	}

	return false
}

// SetKeypairName gets a reference to the given string and assigns it to the KeypairName field.
func (o *AdminInstanceResources) SetKeypairName(v string) {
	o.KeypairName = &v
}

// GetFixedIp returns the FixedIp field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetFixedIp() string {
	if o == nil || IsNil(o.FixedIp) {
		var ret string
		return ret
	}
	return *o.FixedIp
}

// GetFixedIpOk returns a tuple with the FixedIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetFixedIpOk() (*string, bool) {
	if o == nil || IsNil(o.FixedIp) {
		return nil, false
	}
	return o.FixedIp, true
}

// HasFixedIp returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasFixedIp() bool {
	if o != nil && !IsNil(o.FixedIp) {
		return true
	}

	return false
}

// SetFixedIp gets a reference to the given string and assigns it to the FixedIp field.
func (o *AdminInstanceResources) SetFixedIp(v string) {
	o.FixedIp = &v
}

// GetFloatingIp returns the FloatingIp field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetFloatingIp() string {
	if o == nil || IsNil(o.FloatingIp) {
		var ret string
		return ret
	}
	return *o.FloatingIp
}

// GetFloatingIpOk returns a tuple with the FloatingIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetFloatingIpOk() (*string, bool) {
	if o == nil || IsNil(o.FloatingIp) {
		return nil, false
	}
	return o.FloatingIp, true
}

// HasFloatingIp returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasFloatingIp() bool {
	if o != nil && !IsNil(o.FloatingIp) {
		return true
	}

	return false
}

// SetFloatingIp gets a reference to the given string and assigns it to the FloatingIp field.
func (o *AdminInstanceResources) SetFloatingIp(v string) {
	o.FloatingIp = &v
}

// GetContractId returns the ContractId field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetContractId() int32 {
	if o == nil || IsNil(o.ContractId) {
		var ret int32
		return ret
	}
	return *o.ContractId
}

// GetContractIdOk returns a tuple with the ContractId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetContractIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ContractId) {
		return nil, false
	}
	return o.ContractId, true
}

// HasContractId returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasContractId() bool {
	if o != nil && !IsNil(o.ContractId) {
		return true
	}

	return false
}

// SetContractId gets a reference to the given int32 and assigns it to the ContractId field.
func (o *AdminInstanceResources) SetContractId(v int32) {
	o.ContractId = &v
}

// GetFloatingIpStatus returns the FloatingIpStatus field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetFloatingIpStatus() string {
	if o == nil || IsNil(o.FloatingIpStatus) {
		var ret string
		return ret
	}
	return *o.FloatingIpStatus
}

// GetFloatingIpStatusOk returns a tuple with the FloatingIpStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetFloatingIpStatusOk() (*string, bool) {
	if o == nil || IsNil(o.FloatingIpStatus) {
		return nil, false
	}
	return o.FloatingIpStatus, true
}

// HasFloatingIpStatus returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasFloatingIpStatus() bool {
	if o != nil && !IsNil(o.FloatingIpStatus) {
		return true
	}

	return false
}

// SetFloatingIpStatus gets a reference to the given string and assigns it to the FloatingIpStatus field.
func (o *AdminInstanceResources) SetFloatingIpStatus(v string) {
	o.FloatingIpStatus = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AdminInstanceResources) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminInstanceResources) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AdminInstanceResources) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AdminInstanceResources) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o AdminInstanceResources) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminInstanceResources) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OpenstackId) {
		toSerialize["openstack_id"] = o.OpenstackId
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Flavor) {
		toSerialize["flavor"] = o.Flavor
	}
	if !IsNil(o.ImageId) {
		toSerialize["image_id"] = o.ImageId
	}
	if !IsNil(o.VolumeId) {
		toSerialize["volume_id"] = o.VolumeId
	}
	if !IsNil(o.KeypairName) {
		toSerialize["keypair_name"] = o.KeypairName
	}
	if !IsNil(o.FixedIp) {
		toSerialize["fixed_ip"] = o.FixedIp
	}
	if !IsNil(o.FloatingIp) {
		toSerialize["floating_ip"] = o.FloatingIp
	}
	if !IsNil(o.ContractId) {
		toSerialize["contract_id"] = o.ContractId
	}
	if !IsNil(o.FloatingIpStatus) {
		toSerialize["floating_ip_status"] = o.FloatingIpStatus
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableAdminInstanceResources struct {
	value *AdminInstanceResources
	isSet bool
}

func (v NullableAdminInstanceResources) Get() *AdminInstanceResources {
	return v.value
}

func (v *NullableAdminInstanceResources) Set(val *AdminInstanceResources) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminInstanceResources) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminInstanceResources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminInstanceResources(val *AdminInstanceResources) *NullableAdminInstanceResources {
	return &NullableAdminInstanceResources{value: val, isSet: true}
}

func (v NullableAdminInstanceResources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminInstanceResources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


