/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the GPU type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GPU{}

// GPU struct for GPU
type GPU struct {
	Status *bool `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
	Gpu *GPUFields `json:"gpu,omitempty"`
}

// NewGPU instantiates a new GPU object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGPU() *GPU {
	this := GPU{}
	return &this
}

// NewGPUWithDefaults instantiates a new GPU object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGPUWithDefaults() *GPU {
	this := GPU{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GPU) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPU) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GPU) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *GPU) SetStatus(v bool) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GPU) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPU) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GPU) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GPU) SetMessage(v string) {
	o.Message = &v
}

// GetGpu returns the Gpu field value if set, zero value otherwise.
func (o *GPU) GetGpu() GPUFields {
	if o == nil || IsNil(o.Gpu) {
		var ret GPUFields
		return ret
	}
	return *o.Gpu
}

// GetGpuOk returns a tuple with the Gpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPU) GetGpuOk() (*GPUFields, bool) {
	if o == nil || IsNil(o.Gpu) {
		return nil, false
	}
	return o.Gpu, true
}

// HasGpu returns a boolean if a field has been set.
func (o *GPU) HasGpu() bool {
	if o != nil && !IsNil(o.Gpu) {
		return true
	}

	return false
}

// SetGpu gets a reference to the given GPUFields and assigns it to the Gpu field.
func (o *GPU) SetGpu(v GPUFields) {
	o.Gpu = &v
}

func (o GPU) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GPU) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Gpu) {
		toSerialize["gpu"] = o.Gpu
	}
	return toSerialize, nil
}

type NullableGPU struct {
	value *GPU
	isSet bool
}

func (v NullableGPU) Get() *GPU {
	return v.value
}

func (v *NullableGPU) Set(val *GPU) {
	v.value = val
	v.isSet = true
}

func (v NullableGPU) IsSet() bool {
	return v.isSet
}

func (v *NullableGPU) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGPU(val *GPU) *NullableGPU {
	return &NullableGPU{value: val, isSet: true}
}

func (v NullableGPU) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGPU) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


