/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
)

// checks if the VerifyApiKeyPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyApiKeyPayload{}

// VerifyApiKeyPayload struct for VerifyApiKeyPayload
type VerifyApiKeyPayload struct {
	ApiKey *string `json:"api_key,omitempty"`
}

// NewVerifyApiKeyPayload instantiates a new VerifyApiKeyPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyApiKeyPayload() *VerifyApiKeyPayload {
	this := VerifyApiKeyPayload{}
	return &this
}

// NewVerifyApiKeyPayloadWithDefaults instantiates a new VerifyApiKeyPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyApiKeyPayloadWithDefaults() *VerifyApiKeyPayload {
	this := VerifyApiKeyPayload{}
	return &this
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise.
func (o *VerifyApiKeyPayload) GetApiKey() string {
	if o == nil || IsNil(o.ApiKey) {
		var ret string
		return ret
	}
	return *o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyApiKeyPayload) GetApiKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ApiKey) {
		return nil, false
	}
	return o.ApiKey, true
}

// HasApiKey returns a boolean if a field has been set.
func (o *VerifyApiKeyPayload) HasApiKey() bool {
	if o != nil && !IsNil(o.ApiKey) {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given string and assigns it to the ApiKey field.
func (o *VerifyApiKeyPayload) SetApiKey(v string) {
	o.ApiKey = &v
}

func (o VerifyApiKeyPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyApiKeyPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiKey) {
		toSerialize["api_key"] = o.ApiKey
	}
	return toSerialize, nil
}

type NullableVerifyApiKeyPayload struct {
	value *VerifyApiKeyPayload
	isSet bool
}

func (v NullableVerifyApiKeyPayload) Get() *VerifyApiKeyPayload {
	return v.value
}

func (v *NullableVerifyApiKeyPayload) Set(val *VerifyApiKeyPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyApiKeyPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyApiKeyPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyApiKeyPayload(val *VerifyApiKeyPayload) *NullableVerifyApiKeyPayload {
	return &NullableVerifyApiKeyPayload{value: val, isSet: true}
}

func (v NullableVerifyApiKeyPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyApiKeyPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


