/*
Infrahub-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hyperstack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdminHibernationRestorationPayloadModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminHibernationRestorationPayloadModel{}

// AdminHibernationRestorationPayloadModel struct for AdminHibernationRestorationPayloadModel
type AdminHibernationRestorationPayloadModel struct {
	OrgId int32 `json:"org_id"`
	VmName string `json:"vm_name"`
	VmId int32 `json:"vm_id"`
	Status string `json:"status"`
}

type _AdminHibernationRestorationPayloadModel AdminHibernationRestorationPayloadModel

// NewAdminHibernationRestorationPayloadModel instantiates a new AdminHibernationRestorationPayloadModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminHibernationRestorationPayloadModel(orgId int32, vmName string, vmId int32, status string) *AdminHibernationRestorationPayloadModel {
	this := AdminHibernationRestorationPayloadModel{}
	this.OrgId = orgId
	this.VmName = vmName
	this.VmId = vmId
	this.Status = status
	return &this
}

// NewAdminHibernationRestorationPayloadModelWithDefaults instantiates a new AdminHibernationRestorationPayloadModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminHibernationRestorationPayloadModelWithDefaults() *AdminHibernationRestorationPayloadModel {
	this := AdminHibernationRestorationPayloadModel{}
	return &this
}

// GetOrgId returns the OrgId field value
func (o *AdminHibernationRestorationPayloadModel) GetOrgId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *AdminHibernationRestorationPayloadModel) GetOrgIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *AdminHibernationRestorationPayloadModel) SetOrgId(v int32) {
	o.OrgId = v
}

// GetVmName returns the VmName field value
func (o *AdminHibernationRestorationPayloadModel) GetVmName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VmName
}

// GetVmNameOk returns a tuple with the VmName field value
// and a boolean to check if the value has been set.
func (o *AdminHibernationRestorationPayloadModel) GetVmNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VmName, true
}

// SetVmName sets field value
func (o *AdminHibernationRestorationPayloadModel) SetVmName(v string) {
	o.VmName = v
}

// GetVmId returns the VmId field value
func (o *AdminHibernationRestorationPayloadModel) GetVmId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VmId
}

// GetVmIdOk returns a tuple with the VmId field value
// and a boolean to check if the value has been set.
func (o *AdminHibernationRestorationPayloadModel) GetVmIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VmId, true
}

// SetVmId sets field value
func (o *AdminHibernationRestorationPayloadModel) SetVmId(v int32) {
	o.VmId = v
}

// GetStatus returns the Status field value
func (o *AdminHibernationRestorationPayloadModel) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AdminHibernationRestorationPayloadModel) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AdminHibernationRestorationPayloadModel) SetStatus(v string) {
	o.Status = v
}

func (o AdminHibernationRestorationPayloadModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminHibernationRestorationPayloadModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["org_id"] = o.OrgId
	toSerialize["vm_name"] = o.VmName
	toSerialize["vm_id"] = o.VmId
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *AdminHibernationRestorationPayloadModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"org_id",
		"vm_name",
		"vm_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminHibernationRestorationPayloadModel := _AdminHibernationRestorationPayloadModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdminHibernationRestorationPayloadModel)

	if err != nil {
		return err
	}

	*o = AdminHibernationRestorationPayloadModel(varAdminHibernationRestorationPayloadModel)

	return err
}

type NullableAdminHibernationRestorationPayloadModel struct {
	value *AdminHibernationRestorationPayloadModel
	isSet bool
}

func (v NullableAdminHibernationRestorationPayloadModel) Get() *AdminHibernationRestorationPayloadModel {
	return v.value
}

func (v *NullableAdminHibernationRestorationPayloadModel) Set(val *AdminHibernationRestorationPayloadModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminHibernationRestorationPayloadModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminHibernationRestorationPayloadModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminHibernationRestorationPayloadModel(val *AdminHibernationRestorationPayloadModel) *NullableAdminHibernationRestorationPayloadModel {
	return &NullableAdminHibernationRestorationPayloadModel{value: val, isSet: true}
}

func (v NullableAdminHibernationRestorationPayloadModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminHibernationRestorationPayloadModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


